### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by aantron** [tmattio/dream-cli#2]
- [x] Rename `gen-key` to `gen-secret`. Because of the `--key-file` option, it is confusing whether `gen-key` is for generating SSL keyfiles or for secrets. I would rename it to `gen-secret` and replace "secret key" in its description by just "secret." Also, it's not really a key &mdash; the real keys are derived from the secret internally by Dream.
- [x] Show an actual command line that uses `gen-key`.
- [x] Show an actual command line that uses a custom command.
- [ ] ~~Is there a way to pass the pure value given by a custom command down into the Dream app, besides using e.g. a reference?~~

**Comment by outkine** [comment]
What do you mean by "pure value"?

**Comment by aantron** [comment]
Just an ordinary OCaml value. This was the old terminology of Cmdliner.

I'm not sure what I was asking with that point, so I've crossed it off.

**Comment by tmattio** [comment]
Fixed by #4
